### ISSUE TITLE
Marker.getId() deprecated - why exactely?

### ISSUE THREAD

**Issue by black-snow** [mg6maciej/android-maps-extensions#35]
I read http://code.google.com/p/gmaps-api-issues/issues/detail?id=5101 but I couldn't see why it's deprecated.

It's not deprecated on the original marker - why would it be deprecated here? I'm using `getId()` and it works fine. Please tell me what's the issue with `getId()`.

Also, imho, the javadoc should explicitly tell why it's deprecated instead of pointing to an external resource.

**Comment by mg6maciej** [comment]
Using `getId` with AME is disouraged, because it destroys all the optimizations added in AME for marker adding and clustering, for example when using `addMarkersDynamically`. Unless markers are visible and on screen, they are not added to the map, skipping a lot of inter-process communication with Google Play Services. When calling for id, AME needs to create this marker with Google Play Services `GoogleMap.addMarker` call.

In my opinion `getId` on the original Google Mapsn Android v2 library makes no sense and you can normally have `Map<Marker, ModelObject>` when you need to have more data associated with markers. In AME there is also `Marker.setData` and `MarkerOptions.data` for this use case. I see no other point of having ids there.

Do you have any other usecase that I missed?

**Comment by black-snow** [comment]
Guess you're right. I was evaluating the marker ID in `onInfoWindowClick()`. I didn't look up wheter Markers were distinct/comparable so I just took the ID.

Thanks for your explanation.
