### ISSUE TITLE
Marker appear animation

### ISSUE THREAD

**Issue by naivekook** [mg6maciej/android-maps-extensions#47]
Hello there!
First of all thank you very much for his library, it's very cool.

I gonna use it but I have one trouble - I need scale and alpha animation when markers appears on map(after clustering process). I saw that this lib support "Interpolator" for animations, but what about "ValueAnimator"?
Or may be I can do this another way with this library?

**Comment by mg6maciej** [comment]
The library doesn't support `Interpolator` except for animating marker's position with `animatePosition`. If you want to do something similar for when markers appear, you could do that on your own, for example using `Handler` with repeated `Runnable` just like in [MarkerAnimator.java](https://github.com/mg6maciej/android-maps-extensions/blob/develop/android-maps-extensions/src/main/java/com/androidmapsextensions/impl/MarkerAnimator.java).
This can be done outside of the library.
Note that using such animations will most likely not reach 60fps due to Google Play Services limitations. You may instead want to use overlay using Android views and animate that and only put a `Marker` after the animation finishes.
