### ISSUE TITLE
showing cluster icon in place of marker

### ISSUE THREAD

**Issue by manmohanpal3** [mg6maciej/android-maps-extensions#49]
If i have same lat/long for markers then its showing cluster icon not individual marker items when i zoom the map.

**Comment by mg6maciej** [comment]
This is expected behavior and having any changes in AME for this is likely outside the scope. There is no single way to make work for all potential library users.

If you want to display single markers at some zoom level, you may set a `OnCameraChangeListener` or one of the new listeners and change clustering settings to disabled with
```
googleMap.setClutering(ClusteringSettings().enabled(false).addMarkersDynamically(true))
```
and reset it to enabled when zooming out. This just won't work when you have more markers with exactly the same location, because user will not see these markers there.

Another option is just displaying cluster at max zoom level and showing it in info window or with any other UI pattern there are multiple objects there.

If you think there might be a better way, please describe in more details how you would like library to behave.

**Comment by manmohanpal3** [comment]
Thanks for your reply but i have solve this setting some offset value in latitude and longitude if coordinates are same.

 double newLat = user.getLatitude() + (Math.random() - .5) / 1500;
// * (Math.random() * (max - min) + min);

 double newLng = user.getLongitude() + (Math.random() - .5) / 1500;
// * (Math.random() * (max - min) + min);
                   
This solve my problem.
