### ISSUE TITLE
Marker doesn't want to get grouped

### ISSUE THREAD

**Issue by vualeks** [mg6maciej/android-maps-extensions#59]
Hi,

I have a weird problem with one marker on the map that doesn't want to group with the rest of markers when zooming out. I just regularly add a list of markers to the map and they are all in default clustering group 0, but for some reason one of them (and always the same one) doesn't want to group. I don't have any idea why and don't have a clue where to start looking, do you have any suggestions how to debug this, what to check?

Thanks

**Comment by mg6maciej** [comment]
Does it change if you set a different cluster size with `setClustering(new ClusteringSettings().enabled(true).clusterSize(59));`?

**Comment by mg6maciej** [comment]
You may change [`DEBUG_GRID` to true](https://github.com/mg6maciej/android-maps-extensions/blob/fa59228835073a6eb4b8fa08806b0a5f040117b7/android-maps-extensions/src/main/java/com/androidmapsextensions/impl/GridClusteringStrategy.java#L39) and add source of the library to your project instead of as dependency.

This will let you easily see what markers belong to which group at any zoom level.

**Comment by vualeks** [comment]
Great, I'll check it out and let you know abot the results. Thanks

**Comment by vualeks** [comment]
That's it, I played with different clusterSize values and to the result that's working nice.

Great work btw,

Thanks again
